output_root: "results"
site_list_file: "config/sites.txt"
job_titles:
  # VERY COMMON
  - "Data Analyst"
  - "Business Analyst"
  - "Business Systems Analyst"
  - "Business Data Analyst"
  - "Data Engineer"
  - "Data Scientist"
  - "Quality Assurance Engineer"
  - "Python Developer"
  - "AWS Engineer"
  - "AWS Cloud Engineer"
  - "Reporting Analyst"
  - "Fill-Rate Analyst"
  - "Commercial Analytics BA"
  - "PLM Business Analyst"
  - "WMS Business Analyst"
  - "Claims Business Analyst"
  - "Manufacturing Business Analyst"
  - "Quality Business Analyst"

  # COMMON
  - "Systems Business Analyst"
  - "Technical BA"
  - "Insights Analyst"
  - "Operations Data Analyst"
  - "Enrollment & Eligibility Analyst"
  - "EDI Analyst"
  - "Payments Interface Analyst"
  - "Partner Onboarding Analyst"

  # MODERATELY COMMON
  - "Analytics Analyst"
  - "Government Data Analyst"
  - "Program Evaluation Analyst"
  - "Education Outcomes Analyst"
  - "Denials & Appeals Analyst"
  - "Quality Data Analyst"
  - "Quality & Outcomes Analyst"

  #Oracle Titles
  - "Oracle System analyst"
  - "Oracle IT consultant"
  - "Oracle supply chain Techno - functional"
  - "Oracle HCM & Human capital Management"

  # UNCOMMON
  - "Validation Analyst"
  - "Catastrophe Modeling Analyst"
  - "Loss Analytics Analyst"
  - "Network Optimization Analyst"
  - "Grid Analytics Analyst"
  - "Load Forecasting Analyst"

  # NICHE SPECIALIZED (ADVANCED DS)
  - "Education Outcomes Scientist"
  - "Fraud Data Scientist"
  - "Fraud Detection Data Scientist"
  - "NLP Scientist"
  - "Recommendation Systems Scientist"
  - "Risk Modeling Scientist"
  - "Route Optimization Scientist"

keywords:
  - "apply"
  - "jobs"
  - "careers"

regions:
    - "United States"
    - "USA"

days_back: 1
chunk_size: 40

# NEW BLOCK â†’ EXPLICIT JOB TYPE FILTER
job_type:
  modes: "contract,fulltime"

  include_keywords:
    contract:
      - "contract"
      - "contractor"
      - "c2c"
      - "w2"
      - "1099"
      - "contract position"

    fulltime:
      - "full time"
      - "fte"
      - "permanent"
      - "full-time"

    parttime:
      - "part time"

    temp:
      - "temporary"

    internship:
      - "internship"