time_window: "24h"

job_titles:
  - "Data Analyst"
  - "Quality Assurance Engineer"

# All major U.S. regions and synonyms
regions:
  - "United States"
  - "USA"
  - "California"
  - "Texas"
  - "New York"
  - "Florida"
  - "Illinois"
  - "Washington"

# Top ATS domains for IT and enterprise hiring
ats_domains:
    - "randstadusa.com/jobs/"
    - "artech.com/careers"
    - "roberthalf.com/us/en/jobs"
    - "dexian.com/about-us/careers/"
    - "thecsicompanies.com/jobs"
    - "manpower.com/ManpowerUSA/jobs"
    - "tempworks.com/resources/job-seekers/"
    - "jobsusa.hiregenics.com"
    - "monumentconsulting.com/careers"
    - "adeccousa.com/jobs/"
    - "avanthealthcare.com/nursing-jobs-usa/"
    - "ehnn.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_3001/jobs"
    - "careers.employinc.com/search/jobs"
    - "jobs.pdstech.com/jobs/job-search"
    - "innosource.com/job-search/"
    - "work.aequor.com/browse-jobs?"
    - "vanderhouwen.com/job-seekers/"
    - "medicalsolutions.com/jobs/"
    - "tempositions.com/job-board/"
    - "totalmed.com/search"
    - "talsearchgroup.com/jobs/"
    - "aptechstaffing.com/find-a-job/"
    - "anjaneyapinc.com/careers.php"
    - "take2consulting.com/careers"
    - "intone.com/careers-at-intone/"
    - "meetlifesciences.com/job-search/?"
    - "jobs.squiresgroup.com"
    - "careers.maximhealthcare.com"
    - "allegisglobalsolutions.com/en/about-us/jobs"
    - "peakperformers.org/browse-jobs"
    - "3bstaffing.com/jobs/"
    - "aerotek.com/en/jobs"
    - "jobs.partnerspersonnel.com/?"
    - "eteaminc.com/careers/"
    - "huxley.com/en-us/job-search/"
    - "axzoragroup.com/careers/"
    - "fgp.com/job-search/"
    - "webmsi.com/staffing"
    - "engineering.lga.jobs/en/i-am-looking-for-talent/"
    - "productions-plus.com/talent/"
    - "xforia.com/career"
    - "paragonitpros.com/job-board"
    - "insightglobal.com/jobs/"
    - "staffingsme.com/job-portal/"
    - "tandymgroup.com/job-seekers/"
    - "w3global.com/search-jobs"
    - "experis.com/en/for-job-seekers/working-with-experis"
    - "consultnet.com/jobs/"
    - "teksystems.com/en/careers"
    - "techpunditsinc.com/content.html"
    - "altitudestaffing.com/jobs/"
    - "jobdiva.com/portal/"
    - "bcforward.jobs.net/"
    - "combinedcomputer.com/contact/"
    - "mastechdigital.com/careers/"
    - "meridiantechnologies.net/careers/"
    - "cynetsystems.com/careers/"
    - "plumplacementsinc.com/jobs-2/"
    - "theivantagegroup.com/jobs/"
    - "optechus.com/candidates/jobs/"
    - "mamsys.com/careers"
    - "evoketechnologies.com/careers/"
    - "apexsystems.com/careers/job-search"
    - "experis.com/en/opportunities"
    - "careers.akkodis.com/us/en"
    - "kforce.com/find-work/search-jobs/"
    - "roberthalf.com/us/en/jobs/technology"
    - "volt.com/jobs/"
    - "jobs.yoh.com/"
    - "judge.com/jobs/"
    - "eliassen.com/jobs/"
    - "motionrecruitment.com/jobs"
    - "mondo.com/jobs"
    - "advantisglobal.com/jobs"
    - "dexian.com/jobs"
    - "careers.collabera.com/"
    - "diversant.com/jobs"
    - "jobs.beaconhillstaffing.com/"
    - "careers.addisongroup.com/"
    - "jobs.vaco.com/"
    - "thelasallenetwork.com/jobs/"
    - "astoncarter.com/jobs"
    - "insightglobal.com/industries/it/big-data/"
    - "hays.com/jobs"
    - "systemonejobs.com/"
    - "onwardsearch.com/jobs/"
    - "oxfordcorp.com/job-search/"
    - "lucasjamestalent.com/jobs/"
    - "apexon.com/careers/"
    - "planet-technology.com/jobs/"
    - "planet-pharma.com/jobs/"
    - "jobs.theplanetgroup.com/"
    - "jobs.parkerstaffing.com/"
    - "trinet.com"
    - "jobs.prolinkstaffing.com/"
    - "pyramidci.com/jobs"
    - "careers.idctechnologies.com/"
    - "hcltech.com/careers"
    - "jobs.mindlance.com/"
    - "careers.emea.nttdata.com/"
    - "careers.cognizant.com/global/en"
    - "careers.wipro.com/"
    - "careers.infosys.com/"
    - "careers.tcs.com/"
    - "cgi.com/en/careers"
    - "asgn.com/careers"
    - "careers.innovasolutions.com/"
    - "jobs.infinity-cs.com/"
    - "jobs.matrixres.com/en-US/search"
    - "atriumstaff.com/find-a-job/"
    - "jobs.procomservices.com/"
    - "kornferry.com/careers"
    - "spencerstuart.com/careers"
    - "heidrick.com/en/insights"
    - "lucasgroup.com/jobs/"
    - "harveynashusa.com/job-seekers/"
    - "harnham.com/jobs/"
    - "burtchworks.com/job-seekers/"
    - "jobs.smithhanley.com/"
    - "jobs.iqvia.com/"
    - "averityteam.com/jobs"
    - "talution.com/jobs/"
    - "jobs.sparksgroupinc.com/"
    - "onwardselect.com/jobs"
    - "cynetsystems.com/jobs/"
    - "softpath.net/jobs/"
    - "aditiconsulting.com/jobs"
    - "careers.concentrix.com/"
    - "galaxyitech.com/careers/"
    - "careers.bcforward.com/"
    - "nigelfrank.com/us/job-search"
    - "jeffersonfrank.com/job-search"
    - "masonfrank.com/job-search"
    - "revature.com/tech-jobs/"
    - "wavestone.com/en/careers/"
    - "sritechsolutions.com/careers"
    - "zensark.com/careers"
    - "nlbservices.com/jobs/"
    - "westmonroe.com/careers"
    - "ostusa.com/careers"
    - "perficient.com/careers"
    - "jobs.sigmainc.com/"
    - "jobs.alinestaffing.com/"
    - "creativecircle.com/find-work/"
    - "jobs.tential.com/"
    - "jobs.gttit.com/"
    - "abacusservice.com/jobs/"
    - "trinamix.com/careers/"
    - "ltimindtree.com/careers/"
    - "jobs.spectraforce.com/"
    - "careers.pipercompanies.com/"
    - "gotalento.com/jobs"
    - "openarc.net/careers/"
    - "ust.com/en/careers"
    - "theplanetforward.com/jobs/"
    - "tsrconsulting.com/jobs/"
    - "jobs.inspyrsolutions.com/"
    - "ustechsolutions.com/jobs/"
    - "jobs.aequor.com/"
    - "epitec.com/opportunities/"
    - "allegisglobalsolutions.com/en/workforce-solutions"
    - "pivotal-talent.com/jobs"
    - "c2stech.com/careers"
    - "expertek.com/careers"
    - "hanstaffing.com/jobs"
    - "xoriant.com/careers"
    - "tektreeinc.com/careers"
    - "tansoncorp.com/careers"
    - "optomi.com/search-jobs/"
    - "matrix-ifs.com/careers/"
    - "marlabs.com/careers/"
    - "careers.rangam.com/"
    - "jobs.saxonglobal.com/"
    - "talteam.com/careers/"
    - "hanoverit.com/jobs"
    - "solugenix.com/careers"
    - "jobs.brooksource.com/"
    - "talentbridge.com/jobs/"
    - "jobs.medixteam.com/"
    - "jobs.selectgroup.com/"
    - "cybercoders.com/search/"
    - "jobot.com/search"
    - "frankgroup.com/jobs/"
    - "andersonfrank.com/job-search"
    - "washingtonfrank.com/job-search"
    - "nelsonfrank.com/job-search"
    - "michaelpage.com/jobs/technology"
    - "pagepersonnel.com/jobs/technology"
    - "robertwalters.us/job-search.html"
    - "careers.sgainc.com/"
    - "jobs.akraya.com/"
    - "careers.lancesoft.com/"
    - "careers.compunnel.com/"
    - "careers.eteaminc.com/jobs"
    - "aptask.com/jobs/"
    - "careers.sunrisesys.com/"
    - "careers.usmsystems.com/"
    - "vdartinc.com/jobs/"
    - "varite.com/jobs/"
    - "careers.intelliswift.com/"
    - "tekshapers.com/careers"
    - "jobs.agreeya.com/"
    - "zensar.com/careers"
    - "hexaware.com/careers/"
    - "nagarro.com/en/careers"
    - "epam.com/careers"
    - "career.luxoft.com/"
    - "career.softserveinc.com/en-us/vacancies"
    - "dataart.com/careers"
    - "globant.com/careers"
    - "endava.com/careers"
    - "careers.publicissapient.com/"
    - "thoughtworks.com/en-us/careers/jobs"
    - "slalom.com/us/en/careers"
    - "careers.sogeti.com/"
    - "capgemini.com/careers/"
    - "accenture.com/us-en/careers"
    - "apply.deloitte.com/"
    - "wd3.myworkdaysite.com/recruiting/pwc/US"
    - "careers.ey.com/"
    - "us-jobs.kpmg.com/careers"
    - "careers.boozallen.com/"
    - "jobs.saic.com/us/en"
    - "careers.leidos.com/"
    - "gdit.com/careers/search"
    - "careers.caci.com/"
    - "jobs.guidehouse.com/"
    - "protiviti.jobs/"
    - "zs.com/careers"
    - "genpact.com/careers"
    - "techmahindra.com/careers"
    - "persistent.com/careers/"
    - "ness.com/careers/"
    - "hitachivantara.com/en-us/company/careers.html"
    - "careers.us.fujitsu.com/"
    - "jobs.unisys.com/us/en"
    - "hudsonrpo.com/careers/"
    - "lorienglobal.com/jobs"
    - "jobs.bartechstaffing.com/"
    - "horizontal.com/jobs"
    - "hollstadt.com/careers"
    - "queencg.com/jobs"
    - "stand8.io/careers"
    - "cprime.com/careers/"
    - "jobs.altaits.com/"
    - "careers.ceiamerica.com/"
    - "htcinc.com/careers/"
    - "brainworksinc.com/jobs/"
    - "maveris.com/careers"
    - "toptal.com/freelance-jobs"
    - "usebraintrust.com/jobs"
    - "upwork.com/ab/jobs/"
    - "peoplecaddie.com/jobs/"
    - "dice.com/jobs"
    - "hays.com/jobs/it-jobs"
    - "jobspringpartners.com/jobs"
    - "workbridgeassociates.com/jobs"
    - "tekpartners.com/jobs/"
    - "ngagegroup.com/careers"
    - "nextgengr.com/search-jobs/"
    - "jobs.talonpro.com/"
    - "atrilogy.com/careers"
